# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/phasorflim.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1200, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMaximumSize(QtCore.QSize(1200, 800))
        mainWindow.setAutoFillBackground(False)
        mainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_LogConsole = QtWidgets.QLabel(self.centralwidget)
        self.label_LogConsole.setGeometry(QtCore.QRect(10, 610, 91, 17))
        self.label_LogConsole.setObjectName("label_LogConsole")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(340, 90, 20, 661))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_clearLog = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clearLog.setGeometry(QtCore.QRect(260, 610, 71, 25))
        self.pushButton_clearLog.setObjectName("pushButton_clearLog")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 90, 301, 511))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_load = QtWidgets.QWidget()
        self.tab_load.setObjectName("tab_load")
        self.pushButton_LoadPTU = QtWidgets.QPushButton(self.tab_load)
        self.pushButton_LoadPTU.setGeometry(QtCore.QRect(10, 40, 111, 21))
        self.pushButton_LoadPTU.setObjectName("pushButton_LoadPTU")
        self.lineEdit_filepath = QtWidgets.QLineEdit(self.tab_load)
        self.lineEdit_filepath.setGeometry(QtCore.QRect(10, 10, 281, 25))
        self.lineEdit_filepath.setObjectName("lineEdit_filepath")
        self.label_channel = QtWidgets.QLabel(self.tab_load)
        self.label_channel.setGeometry(QtCore.QRect(10, 110, 61, 21))
        self.label_channel.setObjectName("label_channel")
        self.spinBox_channel = QtWidgets.QSpinBox(self.tab_load)
        self.spinBox_channel.setGeometry(QtCore.QRect(210, 110, 61, 25))
        self.spinBox_channel.setMaximum(3)
        self.spinBox_channel.setObjectName("spinBox_channel")
        self.label_spatialBinning = QtWidgets.QLabel(self.tab_load)
        self.label_spatialBinning.setGeometry(QtCore.QRect(10, 150, 101, 21))
        self.label_spatialBinning.setObjectName("label_spatialBinning")
        self.spinBox_spatialBinning = QtWidgets.QSpinBox(self.tab_load)
        self.spinBox_spatialBinning.setGeometry(QtCore.QRect(210, 150, 61, 21))
        self.spinBox_spatialBinning.setMaximum(8)
        self.spinBox_spatialBinning.setObjectName("spinBox_spatialBinning")
        self.label_temporalBinning = QtWidgets.QLabel(self.tab_load)
        self.label_temporalBinning.setGeometry(QtCore.QRect(10, 180, 121, 17))
        self.label_temporalBinning.setObjectName("label_temporalBinning")
        self.spinBox_temporalBinning = QtWidgets.QSpinBox(self.tab_load)
        self.spinBox_temporalBinning.setGeometry(QtCore.QRect(210, 180, 61, 21))
        self.spinBox_temporalBinning.setMaximum(8)
        self.spinBox_temporalBinning.setObjectName("spinBox_temporalBinning")
        self.pushButton_showIntensityImage = QtWidgets.QPushButton(self.tab_load)
        self.pushButton_showIntensityImage.setGeometry(QtCore.QRect(40, 220, 161, 25))
        self.pushButton_showIntensityImage.setObjectName("pushButton_showIntensityImage")
        self.tabWidget.addTab(self.tab_load, "")
        self.tab_setup = QtWidgets.QWidget()
        self.tab_setup.setObjectName("tab_setup")
        self.tabWidget.addTab(self.tab_setup, "")
        self.tab_fitting = QtWidgets.QWidget()
        self.tab_fitting.setObjectName("tab_fitting")
        self.tabWidget.addTab(self.tab_fitting, "")
        self.tab_output = QtWidgets.QWidget()
        self.tab_output.setObjectName("tab_output")
        self.tabWidget.addTab(self.tab_output, "")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(100, 610, 151, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(360, 90, 831, 661))
        self.graphicsView.setObjectName("graphicsView")
        self.logConsole = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.logConsole.setGeometry(QtCore.QRect(10, 640, 321, 111))
        self.logConsole.setObjectName("logConsole")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(mainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.pushButton_showIntensityImage, self.spinBox_temporalBinning)
        mainWindow.setTabOrder(self.spinBox_temporalBinning, self.spinBox_spatialBinning)
        mainWindow.setTabOrder(self.spinBox_spatialBinning, self.pushButton_LoadPTU)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.label_LogConsole.setText(_translate("mainWindow", "Log Console"))
        self.pushButton_clearLog.setText(_translate("mainWindow", "Clear Log"))
        self.pushButton_LoadPTU.setText(_translate("mainWindow", "Load PTU File"))
        self.label_channel.setText(_translate("mainWindow", "Channel"))
        self.label_spatialBinning.setText(_translate("mainWindow", "Spatial Binning"))
        self.label_temporalBinning.setText(_translate("mainWindow", "Temporal Binning"))
        self.pushButton_showIntensityImage.setText(_translate("mainWindow", "Show Intensity Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_load), _translate("mainWindow", "Load"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_setup), _translate("mainWindow", "Setup"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_fitting), _translate("mainWindow", "Fitting"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_output), _translate("mainWindow", "Output"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.actionQuit.setText(_translate("mainWindow", "Quit"))

from pyqtgraph import PlotWidget
