# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/agbp_flimfitter.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1130, 776)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(640, 480))
        mainWindow.setMaximumSize(QtCore.QSize(1900, 2500))
        mainWindow.setAutoFillBackground(False)
        mainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget_menu = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_menu.setMinimumSize(QtCore.QSize(320, 500))
        self.tabWidget_menu.setMaximumSize(QtCore.QSize(320, 12000))
        self.tabWidget_menu.setObjectName("tabWidget_menu")
        self.tab_load = QtWidgets.QWidget()
        self.tab_load.setObjectName("tab_load")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_load)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 10, 199, 214))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.formLayoutWidget)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEdit_filepath = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_filepath.setObjectName("lineEdit_filepath")
        self.gridLayout_7.addWidget(self.lineEdit_filepath, 0, 0, 1, 1)
        self.label_channel = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_channel.setObjectName("label_channel")
        self.gridLayout_7.addWidget(self.label_channel, 2, 0, 1, 1)
        self.spinBox_channel = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_channel.setMaximum(3)
        self.spinBox_channel.setObjectName("spinBox_channel")
        self.gridLayout_7.addWidget(self.spinBox_channel, 2, 2, 1, 1)
        self.label_spatialBinning = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_spatialBinning.setObjectName("label_spatialBinning")
        self.gridLayout_7.addWidget(self.label_spatialBinning, 3, 0, 1, 1)
        self.spinBox_spatialBinning = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_spatialBinning.setMaximum(8)
        self.spinBox_spatialBinning.setObjectName("spinBox_spatialBinning")
        self.gridLayout_7.addWidget(self.spinBox_spatialBinning, 3, 2, 1, 1)
        self.label_temporalBinning = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_temporalBinning.setObjectName("label_temporalBinning")
        self.gridLayout_7.addWidget(self.label_temporalBinning, 4, 0, 1, 1)
        self.spinBox_temporalBinning = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_temporalBinning.setMaximum(8)
        self.spinBox_temporalBinning.setObjectName("spinBox_temporalBinning")
        self.gridLayout_7.addWidget(self.spinBox_temporalBinning, 4, 2, 1, 1)
        self.pushButton_showSelectedDecay = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_showSelectedDecay.setObjectName("pushButton_showSelectedDecay")
        self.gridLayout_7.addWidget(self.pushButton_showSelectedDecay, 6, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.formLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_7.addWidget(self.line, 6, 1, 1, 2)
        self.pushButton_LoadPTU = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_LoadPTU.setObjectName("pushButton_LoadPTU")
        self.gridLayout_7.addWidget(self.pushButton_LoadPTU, 5, 0, 1, 1)
        self.pushButton_selectFile = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_selectFile.setObjectName("pushButton_selectFile")
        self.gridLayout_7.addWidget(self.pushButton_selectFile, 1, 0, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_load)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 240, 311, 441))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_LogConsole = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_LogConsole.setObjectName("label_LogConsole")
        self.gridLayout_4.addWidget(self.label_LogConsole, 4, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_4.addWidget(self.progressBar, 3, 0, 1, 1)
        self.headerPeak = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.headerPeak.setObjectName("headerPeak")
        self.gridLayout_4.addWidget(self.headerPeak, 2, 0, 1, 1)
        self.logConsole = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.logConsole.sizePolicy().hasHeightForWidth())
        self.logConsole.setSizePolicy(sizePolicy)
        self.logConsole.setObjectName("logConsole")
        self.gridLayout_4.addWidget(self.logConsole, 6, 0, 1, 1)
        self.pushButton_clearLog = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_clearLog.setObjectName("pushButton_clearLog")
        self.gridLayout_4.addWidget(self.pushButton_clearLog, 5, 0, 1, 1)
        self.label_headerPeak = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_headerPeak.setObjectName("label_headerPeak")
        self.gridLayout_4.addWidget(self.label_headerPeak, 1, 0, 1, 1)
        self.tabWidget_menu.addTab(self.tab_load, "")
        self.tab_irf = QtWidgets.QWidget()
        self.tab_irf.setObjectName("tab_irf")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_irf)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 311, 801))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_IRFPath = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_IRFPath.setObjectName("label_IRFPath")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_IRFPath)
        self.lineEdit_filePathIRF = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_filePathIRF.setObjectName("lineEdit_filePathIRF")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_filePathIRF)
        self.pushButton_loadIRF = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.pushButton_loadIRF.setObjectName("pushButton_loadIRF")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pushButton_loadIRF)
        self.pushButton_showIRF = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.pushButton_showIRF.setObjectName("pushButton_showIRF")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushButton_showIRF)
        self.label_IRFleftCutoff = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_IRFleftCutoff.setObjectName("label_IRFleftCutoff")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_IRFleftCutoff)
        self.spinBox_irfLeftCut = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.spinBox_irfLeftCut.setMaximum(10000)
        self.spinBox_irfLeftCut.setObjectName("spinBox_irfLeftCut")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinBox_irfLeftCut)
        self.label_IRFrightCutoff = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_IRFrightCutoff.setObjectName("label_IRFrightCutoff")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_IRFrightCutoff)
        self.spinBox_irfRightCut = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.spinBox_irfRightCut.setMaximum(10000)
        self.spinBox_irfRightCut.setProperty("value", 3000)
        self.spinBox_irfRightCut.setObjectName("spinBox_irfRightCut")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinBox_irfRightCut)
        self.label_IRFBackground = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_IRFBackground.setObjectName("label_IRFBackground")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_IRFBackground)
        self.spinBox_IRFBackground = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.spinBox_IRFBackground.setMaximum(100000)
        self.spinBox_IRFBackground.setObjectName("spinBox_IRFBackground")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.spinBox_IRFBackground)
        self.pushButton_resetIRF = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.pushButton_resetIRF.setObjectName("pushButton_resetIRF")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.pushButton_resetIRF)
        self.pushButton_correctIRF = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.pushButton_correctIRF.setObjectName("pushButton_correctIRF")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.pushButton_correctIRF)
        self.tabWidget_menu.addTab(self.tab_irf, "")
        self.tab_fitting = QtWidgets.QWidget()
        self.tab_fitting.setObjectName("tab_fitting")
        self.pushButton_fitImage = QtWidgets.QPushButton(self.tab_fitting)
        self.pushButton_fitImage.setGeometry(QtCore.QRect(0, 690, 101, 25))
        self.pushButton_fitImage.setObjectName("pushButton_fitImage")
        self.listWidget_fittedParameters = QtWidgets.QListWidget(self.tab_fitting)
        self.listWidget_fittedParameters.setGeometry(QtCore.QRect(10, 430, 256, 192))
        self.listWidget_fittedParameters.setObjectName("listWidget_fittedParameters")
        self.label_fittedParameters = QtWidgets.QLabel(self.tab_fitting)
        self.label_fittedParameters.setGeometry(QtCore.QRect(10, 410, 131, 17))
        self.label_fittedParameters.setObjectName("label_fittedParameters")
        self.line_3 = QtWidgets.QFrame(self.tab_fitting)
        self.line_3.setGeometry(QtCore.QRect(0, 390, 291, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_photonThreshold = QtWidgets.QLabel(self.tab_fitting)
        self.label_photonThreshold.setGeometry(QtCore.QRect(130, 660, 121, 20))
        self.label_photonThreshold.setObjectName("label_photonThreshold")
        self.spinBox_photonThreshold = QtWidgets.QSpinBox(self.tab_fitting)
        self.spinBox_photonThreshold.setGeometry(QtCore.QRect(130, 690, 111, 26))
        self.spinBox_photonThreshold.setMaximum(5000)
        self.spinBox_photonThreshold.setSingleStep(50)
        self.spinBox_photonThreshold.setProperty("value", 500)
        self.spinBox_photonThreshold.setObjectName("spinBox_photonThreshold")
        self.spinBox_lifetimeLower = QtWidgets.QSpinBox(self.tab_fitting)
        self.spinBox_lifetimeLower.setGeometry(QtCore.QRect(0, 730, 81, 26))
        self.spinBox_lifetimeLower.setMaximum(10000)
        self.spinBox_lifetimeLower.setSingleStep(100)
        self.spinBox_lifetimeLower.setProperty("value", 2000)
        self.spinBox_lifetimeLower.setObjectName("spinBox_lifetimeLower")
        self.spinBox_lifetimeUpper = QtWidgets.QSpinBox(self.tab_fitting)
        self.spinBox_lifetimeUpper.setGeometry(QtCore.QRect(90, 730, 81, 26))
        self.spinBox_lifetimeUpper.setMaximum(10000)
        self.spinBox_lifetimeUpper.setSingleStep(100)
        self.spinBox_lifetimeUpper.setProperty("value", 3000)
        self.spinBox_lifetimeUpper.setObjectName("spinBox_lifetimeUpper")
        self.pushButton_updateLifetimeImage = QtWidgets.QPushButton(self.tab_fitting)
        self.pushButton_updateLifetimeImage.setGeometry(QtCore.QRect(180, 730, 71, 25))
        self.pushButton_updateLifetimeImage.setAutoDefault(False)
        self.pushButton_updateLifetimeImage.setDefault(False)
        self.pushButton_updateLifetimeImage.setFlat(False)
        self.pushButton_updateLifetimeImage.setObjectName("pushButton_updateLifetimeImage")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.tab_fitting)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(0, 10, 260, 144))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.formLayoutWidget_4)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_objective = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_objective.setObjectName("label_objective")
        self.gridLayout_6.addWidget(self.label_objective, 0, 0, 1, 1)
        self.comboBox_objectiveFunction = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.comboBox_objectiveFunction.setObjectName("comboBox_objectiveFunction")
        self.comboBox_objectiveFunction.addItem("")
        self.comboBox_objectiveFunction.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_objectiveFunction, 0, 1, 1, 1)
        self.label_noExp = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_noExp.setObjectName("label_noExp")
        self.gridLayout_6.addWidget(self.label_noExp, 1, 0, 1, 1)
        self.spinBox_noExp = QtWidgets.QSpinBox(self.formLayoutWidget_4)
        self.spinBox_noExp.setMinimum(1)
        self.spinBox_noExp.setMaximum(5)
        self.spinBox_noExp.setObjectName("spinBox_noExp")
        self.gridLayout_6.addWidget(self.spinBox_noExp, 1, 1, 1, 1)
        self.checkBox_measuredIRFFit = QtWidgets.QCheckBox(self.formLayoutWidget_4)
        self.checkBox_measuredIRFFit.setObjectName("checkBox_measuredIRFFit")
        self.gridLayout_6.addWidget(self.checkBox_measuredIRFFit, 2, 1, 1, 1)
        self.lowerCutoffLabel = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.lowerCutoffLabel.setObjectName("lowerCutoffLabel")
        self.gridLayout_6.addWidget(self.lowerCutoffLabel, 3, 0, 1, 1)
        self.DoubleSpinBox_lowerCutoff = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_4)
        self.DoubleSpinBox_lowerCutoff.setMaximum(10000.0)
        self.DoubleSpinBox_lowerCutoff.setObjectName("DoubleSpinBox_lowerCutoff")
        self.gridLayout_6.addWidget(self.DoubleSpinBox_lowerCutoff, 3, 1, 1, 1)
        self.higherCutoffLabel = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.higherCutoffLabel.setObjectName("higherCutoffLabel")
        self.gridLayout_6.addWidget(self.higherCutoffLabel, 4, 0, 1, 1)
        self.DoubleSpinBox_higherCutoff = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_4)
        self.DoubleSpinBox_higherCutoff.setMaximum(10000.0)
        self.DoubleSpinBox_higherCutoff.setProperty("value", 2800.0)
        self.DoubleSpinBox_higherCutoff.setObjectName("DoubleSpinBox_higherCutoff")
        self.gridLayout_6.addWidget(self.DoubleSpinBox_higherCutoff, 4, 1, 1, 1)
        self.pushButton_fitSelection = QtWidgets.QPushButton(self.tab_fitting)
        self.pushButton_fitSelection.setGeometry(QtCore.QRect(70, 220, 168, 25))
        self.pushButton_fitSelection.setObjectName("pushButton_fitSelection")
        self.tabWidget_menu.addTab(self.tab_fitting, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(0, 10, 233, 231))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_batch_PTUFile = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_batch_PTUFile.setObjectName("label_batch_PTUFile")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_batch_PTUFile)
        self.pushButton_loadBatch = QtWidgets.QPushButton(self.formLayoutWidget_5)
        self.pushButton_loadBatch.setObjectName("pushButton_loadBatch")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton_loadBatch)
        self.label_batch_Channel = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_batch_Channel.setObjectName("label_batch_Channel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_batch_Channel)
        self.spinBox_BatchChannel = QtWidgets.QSpinBox(self.formLayoutWidget_5)
        self.spinBox_BatchChannel.setMaximum(4)
        self.spinBox_BatchChannel.setObjectName("spinBox_BatchChannel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_BatchChannel)
        self.label_batch_Fluorophore = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_batch_Fluorophore.setObjectName("label_batch_Fluorophore")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_batch_Fluorophore)
        self.lineEdit_BatchFluorophore = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.lineEdit_BatchFluorophore.setObjectName("lineEdit_BatchFluorophore")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_BatchFluorophore)
        self.label_batch_Model = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_batch_Model.setObjectName("label_batch_Model")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_batch_Model)
        self.comboBox_BatchModel = QtWidgets.QComboBox(self.formLayoutWidget_5)
        self.comboBox_BatchModel.setMaxVisibleItems(10)
        self.comboBox_BatchModel.setObjectName("comboBox_BatchModel")
        self.comboBox_BatchModel.addItem("")
        self.comboBox_BatchModel.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_BatchModel)
        self.pushButton_fitBatch = QtWidgets.QPushButton(self.formLayoutWidget_5)
        self.pushButton_fitBatch.setObjectName("pushButton_fitBatch")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pushButton_fitBatch)
        self.pushButton_addToBatch = QtWidgets.QPushButton(self.formLayoutWidget_5)
        self.pushButton_addToBatch.setObjectName("pushButton_addToBatch")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.pushButton_addToBatch)
        self.pushButton = QtWidgets.QPushButton(self.formLayoutWidget_5)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.lanbel_Batch_CurrentFile = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.lanbel_Batch_CurrentFile.setObjectName("lanbel_Batch_CurrentFile")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lanbel_Batch_CurrentFile)
        self.currentFileLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.currentFileLineEdit.setObjectName("currentFileLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.currentFileLineEdit)
        self.tabWidget_menu.addTab(self.tab, "")
        self.tab_output = QtWidgets.QWidget()
        self.tab_output.setObjectName("tab_output")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tab_output)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(0, 10, 265, 200))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.formLayoutWidget_3)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton_saveFitResults = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.pushButton_saveFitResults.setObjectName("pushButton_saveFitResults")
        self.gridLayout_8.addWidget(self.pushButton_saveFitResults, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 1, 1, 1, 1)
        self.label_plotHeight = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_plotHeight.setObjectName("label_plotHeight")
        self.gridLayout_8.addWidget(self.label_plotHeight, 2, 0, 1, 1)
        self.spinBox_plotHeight = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.spinBox_plotHeight.setMinimum(2)
        self.spinBox_plotHeight.setMaximum(20)
        self.spinBox_plotHeight.setProperty("value", 6)
        self.spinBox_plotHeight.setObjectName("spinBox_plotHeight")
        self.gridLayout_8.addWidget(self.spinBox_plotHeight, 2, 1, 1, 1)
        self.label_plotWidth = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_plotWidth.setObjectName("label_plotWidth")
        self.gridLayout_8.addWidget(self.label_plotWidth, 3, 0, 1, 1)
        self.spinBox_plotWidth = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.spinBox_plotWidth.setMinimum(2)
        self.spinBox_plotWidth.setMaximum(20)
        self.spinBox_plotWidth.setProperty("value", 5)
        self.spinBox_plotWidth.setObjectName("spinBox_plotWidth")
        self.gridLayout_8.addWidget(self.spinBox_plotWidth, 3, 1, 1, 1)
        self.pushButton_savePlot = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.pushButton_savePlot.setObjectName("pushButton_savePlot")
        self.gridLayout_8.addWidget(self.pushButton_savePlot, 4, 1, 1, 1)
        self.pushButton_saveDecay = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.pushButton_saveDecay.setObjectName("pushButton_saveDecay")
        self.gridLayout_8.addWidget(self.pushButton_saveDecay, 5, 1, 1, 1)
        self.pushButton_saveImage = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.pushButton_saveImage.setObjectName("pushButton_saveImage")
        self.gridLayout_8.addWidget(self.pushButton_saveImage, 6, 1, 1, 1)
        self.tabWidget_menu.addTab(self.tab_output, "")
        self.horizontalLayout.addWidget(self.tabWidget_menu)
        self.tabWidget_view = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_view.setObjectName("tabWidget_view")
        self.tab_intensityimage = QtWidgets.QWidget()
        self.tab_intensityimage.setObjectName("tab_intensityimage")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_intensityimage)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView_intensityimage = GraphicsView(self.tab_intensityimage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_intensityimage.sizePolicy().hasHeightForWidth())
        self.graphicsView_intensityimage.setSizePolicy(sizePolicy)
        self.graphicsView_intensityimage.setMinimumSize(QtCore.QSize(600, 600))
        self.graphicsView_intensityimage.setMaximumSize(QtCore.QSize(10200, 12000))
        self.graphicsView_intensityimage.setObjectName("graphicsView_intensityimage")
        self.gridLayout.addWidget(self.graphicsView_intensityimage, 0, 0, 1, 1)
        self.tabWidget_view.addTab(self.tab_intensityimage, "")
        self.tab_decay = QtWidgets.QWidget()
        self.tab_decay.setObjectName("tab_decay")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_decay)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.graphicsView_decay = PlotWidget(self.tab_decay)
        self.graphicsView_decay.setObjectName("graphicsView_decay")
        self.gridLayout_2.addWidget(self.graphicsView_decay, 0, 0, 1, 1)
        self.tabWidget_view.addTab(self.tab_decay, "")
        self.tab_lifetimeimage = QtWidgets.QWidget()
        self.tab_lifetimeimage.setObjectName("tab_lifetimeimage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_lifetimeimage)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.graphicsView_lifetimeimage = GraphicsView(self.tab_lifetimeimage)
        self.graphicsView_lifetimeimage.setObjectName("graphicsView_lifetimeimage")
        self.gridLayout_3.addWidget(self.graphicsView_lifetimeimage, 0, 0, 1, 1)
        self.tabWidget_view.addTab(self.tab_lifetimeimage, "")
        self.horizontalLayout.addWidget(self.tabWidget_view)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1130, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(mainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(mainWindow)
        self.tabWidget_menu.setCurrentIndex(0)
        self.tabWidget_view.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.lineEdit_filepath, self.pushButton_selectFile)
        mainWindow.setTabOrder(self.pushButton_selectFile, self.spinBox_channel)
        mainWindow.setTabOrder(self.spinBox_channel, self.spinBox_spatialBinning)
        mainWindow.setTabOrder(self.spinBox_spatialBinning, self.spinBox_temporalBinning)
        mainWindow.setTabOrder(self.spinBox_temporalBinning, self.pushButton_LoadPTU)
        mainWindow.setTabOrder(self.pushButton_LoadPTU, self.pushButton_showSelectedDecay)
        mainWindow.setTabOrder(self.pushButton_showSelectedDecay, self.tabWidget_menu)
        mainWindow.setTabOrder(self.tabWidget_menu, self.lineEdit_filePathIRF)
        mainWindow.setTabOrder(self.lineEdit_filePathIRF, self.pushButton_loadIRF)
        mainWindow.setTabOrder(self.pushButton_loadIRF, self.pushButton_showIRF)
        mainWindow.setTabOrder(self.pushButton_showIRF, self.spinBox_irfLeftCut)
        mainWindow.setTabOrder(self.spinBox_irfLeftCut, self.spinBox_irfRightCut)
        mainWindow.setTabOrder(self.spinBox_irfRightCut, self.spinBox_IRFBackground)
        mainWindow.setTabOrder(self.spinBox_IRFBackground, self.pushButton_correctIRF)
        mainWindow.setTabOrder(self.pushButton_correctIRF, self.pushButton_resetIRF)
        mainWindow.setTabOrder(self.pushButton_resetIRF, self.comboBox_objectiveFunction)
        mainWindow.setTabOrder(self.comboBox_objectiveFunction, self.spinBox_noExp)
        mainWindow.setTabOrder(self.spinBox_noExp, self.pushButton_fitSelection)
        mainWindow.setTabOrder(self.pushButton_fitSelection, self.listWidget_fittedParameters)
        mainWindow.setTabOrder(self.listWidget_fittedParameters, self.pushButton_fitImage)
        mainWindow.setTabOrder(self.pushButton_fitImage, self.spinBox_photonThreshold)
        mainWindow.setTabOrder(self.spinBox_photonThreshold, self.spinBox_lifetimeLower)
        mainWindow.setTabOrder(self.spinBox_lifetimeLower, self.spinBox_lifetimeUpper)
        mainWindow.setTabOrder(self.spinBox_lifetimeUpper, self.pushButton_updateLifetimeImage)
        mainWindow.setTabOrder(self.pushButton_updateLifetimeImage, self.pushButton_saveFitResults)
        mainWindow.setTabOrder(self.pushButton_saveFitResults, self.spinBox_plotHeight)
        mainWindow.setTabOrder(self.spinBox_plotHeight, self.spinBox_plotWidth)
        mainWindow.setTabOrder(self.spinBox_plotWidth, self.pushButton_savePlot)
        mainWindow.setTabOrder(self.pushButton_savePlot, self.logConsole)
        mainWindow.setTabOrder(self.logConsole, self.pushButton_clearLog)
        mainWindow.setTabOrder(self.pushButton_clearLog, self.tabWidget_view)
        mainWindow.setTabOrder(self.tabWidget_view, self.graphicsView_intensityimage)
        mainWindow.setTabOrder(self.graphicsView_intensityimage, self.graphicsView_decay)
        mainWindow.setTabOrder(self.graphicsView_decay, self.graphicsView_lifetimeimage)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "AG BP FLIM Fitter"))
        self.label_channel.setText(_translate("mainWindow", "Channel"))
        self.label_spatialBinning.setText(_translate("mainWindow", "Spatial Binning"))
        self.label_temporalBinning.setText(_translate("mainWindow", "Temporal Binning"))
        self.pushButton_showSelectedDecay.setText(_translate("mainWindow", "Show Selected Decay"))
        self.pushButton_LoadPTU.setText(_translate("mainWindow", "Load PTU File"))
        self.pushButton_selectFile.setText(_translate("mainWindow", "Select File"))
        self.label_LogConsole.setText(_translate("mainWindow", "Log Console"))
        self.pushButton_clearLog.setText(_translate("mainWindow", "Clear Log"))
        self.label_headerPeak.setText(_translate("mainWindow", "Header Content"))
        self.tabWidget_menu.setTabText(self.tabWidget_menu.indexOf(self.tab_load), _translate("mainWindow", "Load"))
        self.label_IRFPath.setText(_translate("mainWindow", "Path"))
        self.pushButton_loadIRF.setText(_translate("mainWindow", "Load IRF File"))
        self.pushButton_showIRF.setText(_translate("mainWindow", "Show IRF"))
        self.label_IRFleftCutoff.setText(_translate("mainWindow", "Left Cutoff"))
        self.label_IRFrightCutoff.setText(_translate("mainWindow", "Right Cutoff"))
        self.label_IRFBackground.setText(_translate("mainWindow", "Background"))
        self.pushButton_resetIRF.setText(_translate("mainWindow", "Reset IRF"))
        self.pushButton_correctIRF.setText(_translate("mainWindow", "Correct IRF"))
        self.tabWidget_menu.setTabText(self.tabWidget_menu.indexOf(self.tab_irf), _translate("mainWindow", "IRF"))
        self.pushButton_fitImage.setText(_translate("mainWindow", "Fit Image"))
        self.label_fittedParameters.setText(_translate("mainWindow", "Fitted Parameters"))
        self.label_photonThreshold.setText(_translate("mainWindow", "Photon Threshold"))
        self.pushButton_updateLifetimeImage.setText(_translate("mainWindow", "Update"))
        self.label_objective.setText(_translate("mainWindow", "Objective"))
        self.comboBox_objectiveFunction.setItemText(0, _translate("mainWindow", "Poisson Deviance"))
        self.comboBox_objectiveFunction.setItemText(1, _translate("mainWindow", "Least Squares"))
        self.label_noExp.setText(_translate("mainWindow", "No. Exponentials"))
        self.checkBox_measuredIRFFit.setText(_translate("mainWindow", "Use Measured IRF"))
        self.lowerCutoffLabel.setText(_translate("mainWindow", "Lower Cutoff"))
        self.higherCutoffLabel.setText(_translate("mainWindow", "Higher Cutoff"))
        self.pushButton_fitSelection.setText(_translate("mainWindow", "Fit Selected Decay"))
        self.tabWidget_menu.setTabText(self.tabWidget_menu.indexOf(self.tab_fitting), _translate("mainWindow", "Fitting"))
        self.label_batch_PTUFile.setText(_translate("mainWindow", "Scan Directory"))
        self.pushButton_loadBatch.setText(_translate("mainWindow", "Select"))
        self.label_batch_Channel.setText(_translate("mainWindow", "Channel"))
        self.label_batch_Fluorophore.setText(_translate("mainWindow", "Fluorophore"))
        self.label_batch_Model.setText(_translate("mainWindow", "Model"))
        self.comboBox_BatchModel.setItemText(0, _translate("mainWindow", "Monoexponential"))
        self.comboBox_BatchModel.setItemText(1, _translate("mainWindow", "Biexponential"))
        self.pushButton_fitBatch.setText(_translate("mainWindow", "Fit"))
        self.pushButton_addToBatch.setText(_translate("mainWindow", "Add to Table"))
        self.pushButton.setText(_translate("mainWindow", "Next File"))
        self.lanbel_Batch_CurrentFile.setText(_translate("mainWindow", "Current File"))
        self.tabWidget_menu.setTabText(self.tabWidget_menu.indexOf(self.tab), _translate("mainWindow", "Batch"))
        self.pushButton_saveFitResults.setText(_translate("mainWindow", "Save Parameters as CSV"))
        self.label.setText(_translate("mainWindow", "Generate Plot of Data and Fit"))
        self.label_plotHeight.setText(_translate("mainWindow", "Plot Height"))
        self.label_plotWidth.setText(_translate("mainWindow", "Plot Width"))
        self.pushButton_savePlot.setText(_translate("mainWindow", "Save Plot as PNG"))
        self.pushButton_saveDecay.setText(_translate("mainWindow", "Save Decay and Fit as CSV"))
        self.pushButton_saveImage.setText(_translate("mainWindow", "Save Image as PNG"))
        self.tabWidget_menu.setTabText(self.tabWidget_menu.indexOf(self.tab_output), _translate("mainWindow", "Output"))
        self.tabWidget_view.setTabText(self.tabWidget_view.indexOf(self.tab_intensityimage), _translate("mainWindow", "Intensity Image"))
        self.tabWidget_view.setTabText(self.tabWidget_view.indexOf(self.tab_decay), _translate("mainWindow", "Decay"))
        self.tabWidget_view.setTabText(self.tabWidget_view.indexOf(self.tab_lifetimeimage), _translate("mainWindow", "Lifetime Image"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.actionQuit.setText(_translate("mainWindow", "Quit"))

from pyqtgraph import GraphicsView, PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

