# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/agbp_flimfitter.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1230, 893)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(640, 480))
        mainWindow.setMaximumSize(QtCore.QSize(1900, 2500))
        mainWindow.setAutoFillBackground(False)
        mainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget_menu = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_menu.setMinimumSize(QtCore.QSize(320, 500))
        self.tabWidget_menu.setMaximumSize(QtCore.QSize(320, 12000))
        self.tabWidget_menu.setObjectName("tabWidget_menu")
        self.tab_load = QtWidgets.QWidget()
        self.tab_load.setObjectName("tab_load")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_load)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 10, 311, 231))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lineEdit_filepath = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_filepath.setObjectName("lineEdit_filepath")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.lineEdit_filepath)
        self.pushButton_selectFile = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_selectFile.setObjectName("pushButton_selectFile")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_selectFile)
        self.label_channel = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_channel.setObjectName("label_channel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_channel)
        self.spinBox_channel = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_channel.setMaximum(3)
        self.spinBox_channel.setObjectName("spinBox_channel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox_channel)
        self.label_spatialBinning = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_spatialBinning.setObjectName("label_spatialBinning")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_spatialBinning)
        self.spinBox_spatialBinning = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_spatialBinning.setMaximum(8)
        self.spinBox_spatialBinning.setObjectName("spinBox_spatialBinning")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBox_spatialBinning)
        self.label_temporalBinning = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_temporalBinning.setObjectName("label_temporalBinning")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_temporalBinning)
        self.spinBox_temporalBinning = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_temporalBinning.setMaximum(8)
        self.spinBox_temporalBinning.setObjectName("spinBox_temporalBinning")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinBox_temporalBinning)
        self.pushButton_LoadPTU = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_LoadPTU.setObjectName("pushButton_LoadPTU")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.pushButton_LoadPTU)
        self.line = QtWidgets.QFrame(self.formLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.line)
        self.pushButton_showSelectedDecay = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_showSelectedDecay.setObjectName("pushButton_showSelectedDecay")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.pushButton_showSelectedDecay)
        self.label_LogConsole = QtWidgets.QLabel(self.tab_load)
        self.label_LogConsole.setGeometry(QtCore.QRect(0, 520, 84, 17))
        self.label_LogConsole.setObjectName("label_LogConsole")
        self.progressBar = QtWidgets.QProgressBar(self.tab_load)
        self.progressBar.setGeometry(QtCore.QRect(30, 490, 251, 25))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_clearLog = QtWidgets.QPushButton(self.tab_load)
        self.pushButton_clearLog.setGeometry(QtCore.QRect(230, 520, 80, 25))
        self.pushButton_clearLog.setObjectName("pushButton_clearLog")
        self.logConsole = QtWidgets.QPlainTextEdit(self.tab_load)
        self.logConsole.setGeometry(QtCore.QRect(0, 550, 311, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.logConsole.sizePolicy().hasHeightForWidth())
        self.logConsole.setSizePolicy(sizePolicy)
        self.logConsole.setObjectName("logConsole")
        self.label_headerPeak = QtWidgets.QLabel(self.tab_load)
        self.label_headerPeak.setGeometry(QtCore.QRect(0, 250, 111, 17))
        self.label_headerPeak.setObjectName("label_headerPeak")
        self.listWidget_headerPeak = QtWidgets.QListWidget(self.tab_load)
        self.listWidget_headerPeak.setGeometry(QtCore.QRect(0, 270, 311, 211))
        self.listWidget_headerPeak.setObjectName("listWidget_headerPeak")
        self.tabWidget_menu.addTab(self.tab_load, "")
        self.tab_irf = QtWidgets.QWidget()
        self.tab_irf.setObjectName("tab_irf")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_irf)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 311, 801))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.pushButton_loadIRF = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.pushButton_loadIRF.setObjectName("pushButton_loadIRF")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pushButton_loadIRF)
        self.pushButton_showIRF = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.pushButton_showIRF.setObjectName("pushButton_showIRF")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushButton_showIRF)
        self.spinBox_irfRightCut = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.spinBox_irfRightCut.setMaximum(10000)
        self.spinBox_irfRightCut.setProperty("value", 3000)
        self.spinBox_irfRightCut.setObjectName("spinBox_irfRightCut")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinBox_irfRightCut)
        self.spinBox_irfLeftCut = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.spinBox_irfLeftCut.setMaximum(10000)
        self.spinBox_irfLeftCut.setObjectName("spinBox_irfLeftCut")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinBox_irfLeftCut)
        self.spinBox_IRFBackground = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.spinBox_IRFBackground.setMaximum(100000)
        self.spinBox_IRFBackground.setObjectName("spinBox_IRFBackground")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.spinBox_IRFBackground)
        self.label_IRFleftCutoff = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_IRFleftCutoff.setObjectName("label_IRFleftCutoff")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_IRFleftCutoff)
        self.label_IRFrightCutoff = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_IRFrightCutoff.setObjectName("label_IRFrightCutoff")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_IRFrightCutoff)
        self.label_IRFBackground = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_IRFBackground.setObjectName("label_IRFBackground")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_IRFBackground)
        self.lineEdit_filePathIRF = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_filePathIRF.setObjectName("lineEdit_filePathIRF")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_filePathIRF)
        self.label_IRFPath = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_IRFPath.setObjectName("label_IRFPath")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_IRFPath)
        self.pushButton_correctIRF = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.pushButton_correctIRF.setObjectName("pushButton_correctIRF")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.pushButton_correctIRF)
        self.pushButton_resetIRF = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.pushButton_resetIRF.setObjectName("pushButton_resetIRF")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.pushButton_resetIRF)
        self.pushButton_fitIRF = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.pushButton_fitIRF.setObjectName("pushButton_fitIRF")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.pushButton_fitIRF)
        self.checkBox_useFittedIRF = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.checkBox_useFittedIRF.setObjectName("checkBox_useFittedIRF")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.checkBox_useFittedIRF)
        self.tabWidget_menu.addTab(self.tab_irf, "")
        self.tab_fitting = QtWidgets.QWidget()
        self.tab_fitting.setObjectName("tab_fitting")
        self.pushButton_fitImage = QtWidgets.QPushButton(self.tab_fitting)
        self.pushButton_fitImage.setGeometry(QtCore.QRect(0, 690, 101, 25))
        self.pushButton_fitImage.setObjectName("pushButton_fitImage")
        self.listWidget_fittedParameters = QtWidgets.QListWidget(self.tab_fitting)
        self.listWidget_fittedParameters.setGeometry(QtCore.QRect(10, 430, 256, 192))
        self.listWidget_fittedParameters.setObjectName("listWidget_fittedParameters")
        self.label_fittedParameters = QtWidgets.QLabel(self.tab_fitting)
        self.label_fittedParameters.setGeometry(QtCore.QRect(10, 410, 131, 17))
        self.label_fittedParameters.setObjectName("label_fittedParameters")
        self.line_3 = QtWidgets.QFrame(self.tab_fitting)
        self.line_3.setGeometry(QtCore.QRect(0, 390, 291, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_photonThreshold = QtWidgets.QLabel(self.tab_fitting)
        self.label_photonThreshold.setGeometry(QtCore.QRect(130, 660, 121, 20))
        self.label_photonThreshold.setObjectName("label_photonThreshold")
        self.spinBox_photonThreshold = QtWidgets.QSpinBox(self.tab_fitting)
        self.spinBox_photonThreshold.setGeometry(QtCore.QRect(130, 690, 111, 26))
        self.spinBox_photonThreshold.setMaximum(5000)
        self.spinBox_photonThreshold.setSingleStep(50)
        # self.spinBox_photonThreshold.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spinBox_photonThreshold.setProperty("value", 500)
        self.spinBox_photonThreshold.setObjectName("spinBox_photonThreshold")
        self.spinBox_lifetimeLower = QtWidgets.QSpinBox(self.tab_fitting)
        self.spinBox_lifetimeLower.setGeometry(QtCore.QRect(0, 730, 81, 26))
        self.spinBox_lifetimeLower.setMaximum(10000)
        self.spinBox_lifetimeLower.setSingleStep(100)
        self.spinBox_lifetimeLower.setProperty("value", 2000)
        self.spinBox_lifetimeLower.setObjectName("spinBox_lifetimeLower")
        self.spinBox_lifetimeUpper = QtWidgets.QSpinBox(self.tab_fitting)
        self.spinBox_lifetimeUpper.setGeometry(QtCore.QRect(90, 730, 81, 26))
        self.spinBox_lifetimeUpper.setMaximum(10000)
        self.spinBox_lifetimeUpper.setSingleStep(100)
        self.spinBox_lifetimeUpper.setProperty("value", 3000)
        self.spinBox_lifetimeUpper.setObjectName("spinBox_lifetimeUpper")
        self.pushButton_updateLifetimeImage = QtWidgets.QPushButton(self.tab_fitting)
        self.pushButton_updateLifetimeImage.setGeometry(QtCore.QRect(180, 730, 71, 25))
        self.pushButton_updateLifetimeImage.setAutoDefault(False)
        self.pushButton_updateLifetimeImage.setDefault(False)
        self.pushButton_updateLifetimeImage.setFlat(False)
        self.pushButton_updateLifetimeImage.setObjectName("pushButton_updateLifetimeImage")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.tab_fitting)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(0, 10, 311, 201))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_objective = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_objective.setObjectName("label_objective")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_objective)
        self.comboBox_objectiveFunction = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.comboBox_objectiveFunction.setObjectName("comboBox_objectiveFunction")
        self.comboBox_objectiveFunction.addItem("")
        self.comboBox_objectiveFunction.addItem("")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_objectiveFunction)
        self.label_noExp = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_noExp.setObjectName("label_noExp")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_noExp)
        self.spinBox_noExp = QtWidgets.QSpinBox(self.formLayoutWidget_4)
        self.spinBox_noExp.setMinimum(1)
        self.spinBox_noExp.setMaximum(5)
        self.spinBox_noExp.setObjectName("spinBox_noExp")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_noExp)
        self.pushButton_fitSelection = QtWidgets.QPushButton(self.tab_fitting)
        self.pushButton_fitSelection.setGeometry(QtCore.QRect(70, 220, 168, 25))
        self.pushButton_fitSelection.setObjectName("pushButton_fitSelection")
        self.tabWidget_menu.addTab(self.tab_fitting, "")
        self.tab_output = QtWidgets.QWidget()
        self.tab_output.setObjectName("tab_output")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tab_output)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(0, 10, 311, 201))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.pushButton_saveFitResults = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.pushButton_saveFitResults.setObjectName("pushButton_saveFitResults")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton_saveFitResults)
        self.label = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label)
        self.label_plotHeight = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_plotHeight.setObjectName("label_plotHeight")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_plotHeight)
        self.spinBox_plotHeight = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.spinBox_plotHeight.setObjectName("spinBox_plotHeight")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_plotHeight)
        self.label_plotWidth = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_plotWidth.setObjectName("label_plotWidth")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_plotWidth)
        self.spinBox_plotWidth = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.spinBox_plotWidth.setObjectName("spinBox_plotWidth")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox_plotWidth)
        self.pushButton_savePlot = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.pushButton_savePlot.setObjectName("pushButton_savePlot")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pushButton_savePlot)
        self.tabWidget_menu.addTab(self.tab_output, "")
        self.horizontalLayout.addWidget(self.tabWidget_menu)
        self.tabWidget_view = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_view.setObjectName("tabWidget_view")
        self.tab_intensityimage = QtWidgets.QWidget()
        self.tab_intensityimage.setObjectName("tab_intensityimage")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_intensityimage)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView_intensityimage = GraphicsView(self.tab_intensityimage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_intensityimage.sizePolicy().hasHeightForWidth())
        self.graphicsView_intensityimage.setSizePolicy(sizePolicy)
        self.graphicsView_intensityimage.setMinimumSize(QtCore.QSize(600, 600))
        self.graphicsView_intensityimage.setMaximumSize(QtCore.QSize(10200, 12000))
        self.graphicsView_intensityimage.setObjectName("graphicsView_intensityimage")
        self.gridLayout.addWidget(self.graphicsView_intensityimage, 0, 0, 1, 1)
        self.tabWidget_view.addTab(self.tab_intensityimage, "")
        self.tab_decay = QtWidgets.QWidget()
        self.tab_decay.setObjectName("tab_decay")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_decay)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.graphicsView_decay = PlotWidget(self.tab_decay)
        self.graphicsView_decay.setObjectName("graphicsView_decay")
        self.gridLayout_2.addWidget(self.graphicsView_decay, 0, 0, 1, 1)
        self.tabWidget_view.addTab(self.tab_decay, "")
        self.tab_lifetimeimage = QtWidgets.QWidget()
        self.tab_lifetimeimage.setObjectName("tab_lifetimeimage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_lifetimeimage)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.graphicsView_lifetimeimage = GraphicsView(self.tab_lifetimeimage)
        self.graphicsView_lifetimeimage.setObjectName("graphicsView_lifetimeimage")
        self.gridLayout_3.addWidget(self.graphicsView_lifetimeimage, 0, 0, 1, 1)
        self.tabWidget_view.addTab(self.tab_lifetimeimage, "")
        self.horizontalLayout.addWidget(self.tabWidget_view)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1230, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(mainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(mainWindow)
        self.tabWidget_menu.setCurrentIndex(0)
        self.tabWidget_view.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.lineEdit_filepath, self.pushButton_selectFile)
        mainWindow.setTabOrder(self.pushButton_selectFile, self.spinBox_channel)
        mainWindow.setTabOrder(self.spinBox_channel, self.spinBox_spatialBinning)
        mainWindow.setTabOrder(self.spinBox_spatialBinning, self.spinBox_temporalBinning)
        mainWindow.setTabOrder(self.spinBox_temporalBinning, self.pushButton_LoadPTU)
        mainWindow.setTabOrder(self.pushButton_LoadPTU, self.pushButton_showSelectedDecay)
        mainWindow.setTabOrder(self.pushButton_showSelectedDecay, self.tabWidget_menu)
        mainWindow.setTabOrder(self.tabWidget_menu, self.lineEdit_filePathIRF)
        mainWindow.setTabOrder(self.lineEdit_filePathIRF, self.pushButton_loadIRF)
        mainWindow.setTabOrder(self.pushButton_loadIRF, self.pushButton_showIRF)
        mainWindow.setTabOrder(self.pushButton_showIRF, self.spinBox_irfLeftCut)
        mainWindow.setTabOrder(self.spinBox_irfLeftCut, self.spinBox_irfRightCut)
        mainWindow.setTabOrder(self.spinBox_irfRightCut, self.spinBox_IRFBackground)
        mainWindow.setTabOrder(self.spinBox_IRFBackground, self.pushButton_correctIRF)
        mainWindow.setTabOrder(self.pushButton_correctIRF, self.pushButton_fitIRF)
        mainWindow.setTabOrder(self.pushButton_fitIRF, self.checkBox_useFittedIRF)
        mainWindow.setTabOrder(self.checkBox_useFittedIRF, self.pushButton_resetIRF)
        mainWindow.setTabOrder(self.pushButton_resetIRF, self.comboBox_objectiveFunction)
        mainWindow.setTabOrder(self.comboBox_objectiveFunction, self.spinBox_noExp)
        mainWindow.setTabOrder(self.spinBox_noExp, self.pushButton_fitSelection)
        mainWindow.setTabOrder(self.pushButton_fitSelection, self.listWidget_fittedParameters)
        mainWindow.setTabOrder(self.listWidget_fittedParameters, self.pushButton_fitImage)
        mainWindow.setTabOrder(self.pushButton_fitImage, self.spinBox_photonThreshold)
        mainWindow.setTabOrder(self.spinBox_photonThreshold, self.spinBox_lifetimeLower)
        mainWindow.setTabOrder(self.spinBox_lifetimeLower, self.spinBox_lifetimeUpper)
        mainWindow.setTabOrder(self.spinBox_lifetimeUpper, self.pushButton_updateLifetimeImage)
        mainWindow.setTabOrder(self.pushButton_updateLifetimeImage, self.pushButton_saveFitResults)
        mainWindow.setTabOrder(self.pushButton_saveFitResults, self.spinBox_plotHeight)
        mainWindow.setTabOrder(self.spinBox_plotHeight, self.spinBox_plotWidth)
        mainWindow.setTabOrder(self.spinBox_plotWidth, self.pushButton_savePlot)
        mainWindow.setTabOrder(self.pushButton_savePlot, self.logConsole)
        mainWindow.setTabOrder(self.logConsole, self.pushButton_clearLog)
        mainWindow.setTabOrder(self.pushButton_clearLog, self.tabWidget_view)
        mainWindow.setTabOrder(self.tabWidget_view, self.graphicsView_intensityimage)
        mainWindow.setTabOrder(self.graphicsView_intensityimage, self.graphicsView_decay)
        mainWindow.setTabOrder(self.graphicsView_decay, self.graphicsView_lifetimeimage)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "AG BP FLIM Fitter"))
        self.pushButton_selectFile.setText(_translate("mainWindow", "Select File"))
        self.label_channel.setText(_translate("mainWindow", "Channel"))
        self.label_spatialBinning.setText(_translate("mainWindow", "Spatial Binning"))
        self.label_temporalBinning.setText(_translate("mainWindow", "Temporal Binning"))
        self.pushButton_LoadPTU.setText(_translate("mainWindow", "Load PTU File"))
        self.pushButton_showSelectedDecay.setText(_translate("mainWindow", "Show Selected Decay"))
        self.label_LogConsole.setText(_translate("mainWindow", "Log Console"))
        self.pushButton_clearLog.setText(_translate("mainWindow", "Clear Log"))
        self.label_headerPeak.setText(_translate("mainWindow", "Header Content"))
        self.tabWidget_menu.setTabText(self.tabWidget_menu.indexOf(self.tab_load), _translate("mainWindow", "Load"))
        self.pushButton_loadIRF.setText(_translate("mainWindow", "Load IRF File"))
        self.pushButton_showIRF.setText(_translate("mainWindow", "Show IRF"))
        self.label_IRFleftCutoff.setText(_translate("mainWindow", "Left Cutoff"))
        self.label_IRFrightCutoff.setText(_translate("mainWindow", "Right Cutoff"))
        self.label_IRFBackground.setText(_translate("mainWindow", "Background"))
        self.label_IRFPath.setText(_translate("mainWindow", "Path"))
        self.pushButton_correctIRF.setText(_translate("mainWindow", "Correct IRF"))
        self.pushButton_resetIRF.setText(_translate("mainWindow", "Reset IRF"))
        self.pushButton_fitIRF.setText(_translate("mainWindow", "Fit IRF"))
        self.checkBox_useFittedIRF.setText(_translate("mainWindow", "Use Fitted IRF"))
        self.tabWidget_menu.setTabText(self.tabWidget_menu.indexOf(self.tab_irf), _translate("mainWindow", "IRF"))
        self.pushButton_fitImage.setText(_translate("mainWindow", "Fit Image"))
        self.label_fittedParameters.setText(_translate("mainWindow", "Fitted Parameters"))
        self.label_photonThreshold.setText(_translate("mainWindow", "Photon Threshold"))
        self.pushButton_updateLifetimeImage.setText(_translate("mainWindow", "Update"))
        self.label_objective.setText(_translate("mainWindow", "Objective"))
        self.comboBox_objectiveFunction.setItemText(0, _translate("mainWindow", "Poisson Deviance"))
        self.comboBox_objectiveFunction.setItemText(1, _translate("mainWindow", "Least Squares"))
        self.label_noExp.setText(_translate("mainWindow", "No. Exponentials"))
        self.pushButton_fitSelection.setText(_translate("mainWindow", "Fit Selected Decay"))
        self.tabWidget_menu.setTabText(self.tabWidget_menu.indexOf(self.tab_fitting), _translate("mainWindow", "Fitting"))
        self.pushButton_saveFitResults.setText(_translate("mainWindow", "Save Parameters as CSV"))
        self.label.setText(_translate("mainWindow", "Generate Plot of Data and Fit"))
        self.label_plotHeight.setText(_translate("mainWindow", "Plot Height"))
        self.label_plotWidth.setText(_translate("mainWindow", "Plot Width"))
        self.pushButton_savePlot.setText(_translate("mainWindow", "Save Plot as PNG"))
        self.tabWidget_menu.setTabText(self.tabWidget_menu.indexOf(self.tab_output), _translate("mainWindow", "Output"))
        self.tabWidget_view.setTabText(self.tabWidget_view.indexOf(self.tab_intensityimage), _translate("mainWindow", "Intensity Image"))
        self.tabWidget_view.setTabText(self.tabWidget_view.indexOf(self.tab_decay), _translate("mainWindow", "Decay"))
        self.tabWidget_view.setTabText(self.tabWidget_view.indexOf(self.tab_lifetimeimage), _translate("mainWindow", "Lifetime Image"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.actionQuit.setText(_translate("mainWindow", "Quit"))

from pyqtgraph import GraphicsView, PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

