// Modules to control application life and create native browser window
const { app, BrowserWindow } = require('electron')
const path = require('path');
const ipc = require("electron").ipcMain;
const dialog = require("electron").dialog;
const fs = require("fs");
const { PythonShell } = require("python-shell")
const child_process = require("child_process");

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let mainWindow, progressbar;

function createWindow() {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    width: 1100, height: 800
  });

  // and load the index.html of the app.
  mainWindow.loadFile('app.html');

  // Open the DevTools.
  // mainWindow.webContents.openDevTools()

  // Emitted when the window is closed.
  mainWindow.on('closed', function () {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null;
  });
};


// Increasing the max RAM available to electron
app.commandLine.appendSwitch('js-flags', '--max-old-space-size=8192');


// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', function () {
  createWindow();
});

// Quit when all windows are closed.
app.on('window-all-closed', function () {
  // On OS X it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit()
  };
});

app.on('activate', function () {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (mainWindow === null) {
    createWindow()
  };
});


// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.


// IPC receivers for processing fs tasks

ipc.on("ptu-filepath", function (event) {
  dialog.showOpenDialog(mainWindow, {
    title: "Select your .ptu file",
    defaultPath: "/Users/<username>/Documents/",
    buttonLabel: "Decode this .ptu file",
    properties: ["openFile"]
  }, function (file) {
    if (file) {
      event.sender.send("selectedptu", file);
    };
  })
});





// Progress bar
ipc.on("start-progressbar", function (event) {
  progressbar = new BrowserWindow({
    width: 300,
    height: 125,
    resizable: false,
    parent: mainWindow,
    modal: true,
    alwaysOnTop: true
  });
  progressbar.loadFile("progressbar.html");
  progressbar.show();
});

ipc.on("update-progressbar", function (event, data) {
  var message = data[0];
  var progress = data[1];
  progressbar.webContents.send("update-progressbar", [message, progress]);
});

ipc.on("end-progressbar", function (event) {
  progressbar.close();
  progressbar = null;
});


// Receiving intensity image as base64 and write to file sytem

ipc.on("intensity-image-base64", function (event, data) {
  let startPath = "";

  if (process.platform === "darwin") {
    startPath = "/Users/<username>/Documents/"
  };

  dialog.showSaveDialog(mainWindow, {
    title: "Save Intensity Image ...",
    defaultPath: startPath + "img.jpeg",
    buttonLabel: "Save",
    filters: [{
      name: "Image/JPEG",
      extensions: ["jpeg"]
    }]
  }, function (file) {
    console.log("Selected directory: " + file)

    if (file) {
      let imgData = data;
      fs.writeFile(file, imgData, "base64", function (err) {
        if (err === null) {
          console.log("The intensity image was saved successfully!")
        } else {
          console.log("An error occured during saveing the intensity image: " + err)
        }
      });
    }
  });
});



// Receiving lifetime hist from renderer.js for writing to disk as csv
ipc.on("saveLifetimeHistAsCSV", function (event, data) {
  let startPath = "";
  if (process.platform === "darwin") {
    startPath = "/Users/<username>/Documents/"
  };

  dialog.showSaveDialog(mainWindow, {
    title: "Save Lifetime Histogram ...",
    defaultPath: startPath + "lifetimeHist.csv",
    buttonLabel: "Save",
    filters: [{
      name: "CSV",
      extensions: ["csv"]
    }]
  }, function (file) {
    console.log("Writing lifetime histogram as: " + file)

    if (file) {
      var tmp, i;

      // Creating write stream to user-selected location
      var csvWriteStream = fs.createWriteStream(file);

      // Writing header section
      csvWriteStream.write(["Lifetime Histogram Data Generated by Phasor FLIM"].toString() + "\n \n");
      csvWriteStream.write(["Lifetime", "Counts"].toString() + "\n");

      for (i = 0; i < data[0]._data.length; i++) {
        tmp = [data[0]._data[i], data[1][i]].toString();
        csvWriteStream.write(tmp + "\n");
      };

      csvWriteStream.close();
    };
  });

});

// Receiving phasor coordinates and writing to csv
ipc.on("savePhasorCoordinatesAsCSV", function (event, data) {
  let startPath = "";
  if (process.platform === "darwin") {
    startPath = "/Users/<username>/Documents/"
  };

  dialog.showSaveDialog(mainWindow, {
    title: "Save Phasor Coordinates ...",
    defaultPath: startPath + "phasors.csv",
    buttonLabel: "Save",
    filters: [{
      name: "CSV",
      extensions: ["csv"]
    }]
  }, function (file) {
    console.log("Writing phasor coordinates as: " + file)

    if (file) {
      var tmp, i, x, y;

      // Creating write stream to user-selected location
      var csvWriteStream = fs.createWriteStream(file);

      // // Writing header section
      csvWriteStream.write(["Phasor Coordinates generated by Phasor FLIM"].toString() + "\n \n");
      csvWriteStream.write(["g", "s"].toString() + "\n");

      for (x = 0; x < data.length; x++) {
        for (y = 0; y < data[0].length; y++) {
          if (data[x][y][0] != undefined && data[x][y][1] != undefined) {
            tmp = [data[x][y][0], data[x][y][1]].toString();
            csvWriteStream.write(tmp + "\n");
          };
        };
      };

      csvWriteStream.close();
    };
  });
});









// Python Test Area




/* let pythonOptions = {
  mode: "text",
  pythonOptions: ["-u"],
  args: [path.join(__dirname ,"testData/EGFP_Cherry_Co_1_1.ptu")]
};

PythonShell.run("filedecoding/PTUReader.py", pythonOptions, function (err, output) {
  if (err) throw err;

  console.log("Python Output: %j" % output);
}) */